In [1]:
import numpy as np
import pandas as pd

In [2]:
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [4]:
arr1.shape

(3,)

In [5]:
df_list1 = pd.DataFrame(list1)
df_arr1 = pd.DataFrame(arr1)
print(df_arr1)
print(df_list1)

   0
0  1
1  2
2  3
   0
0  1
1  2
2  3


In [6]:
df_list1

0
0  1
1  2
2  3

In [7]:
df_arr1

0
0  1
1  2
2  3

In [8]:
df_list1.columns = ['kor']

In [9]:
df_list1

kor
0    1
1    2
2    3

In [15]:
a = df_list1.columns
a

Index(['kor'], dtype='object')

In [11]:
print(pd.__version__)

1.1.0


In [14]:
type(a)

pandas.core.indexes.base.Index

In [16]:
df_arr1

0
0  1
1  2
2  3

In [17]:
df_arr1.columns = ['eng']

In [18]:
df_arr1

eng
0    1
1    2
2    3

In [ ]:
df_arr1

In [21]:
# 2차원 데이터셋으로 DataFrame 생성
list2 = [
    [1,  2,  3]
  , [11,12, 13]
]
list2

[[1, 2, 3], [11, 12, 13]]

In [23]:
df_list2 = pd.DataFrame(list2)
df_list2

0   1   2
0   1   2   3
1  11  12  13

In [29]:
df_list2.columns=['kor','eng','mat']

In [30]:
df_list2

kor  eng  mat
0    1    2    3
1   11   12   13

In [42]:
dict_= {
     'kor':[1,11]
    ,'eng':[2,12]
    ,'mat':[3,13]
}
dict_

{'kor': [1, 11], 'eng': [2, 12], 'mat': [3, 13]}

In [43]:
df_dict_ = pd.DataFrame(dict_)
df_dict_

kor  eng  mat
0    1    2    3
1   11   12   13

In [44]:
arr3 = df_dict_.values
arr3

array([[ 1,  2,  3],
       [11, 12, 13]], dtype=int64)

In [45]:
type(arr3)

numpy.ndarray

In [46]:
id(arr3)

2802391344992

In [47]:
arr3.shape

(2, 3)

In [49]:
arr3.ndim

2

In [51]:
# DataFrame => list 로 변환
# df_dict_ : DataFrame
# df_dict.values : ndarray
# df_dict.values.tolist() : list
list3 = df_dict_.values.tolist()
list3

[[1, 2, 3], [11, 12, 13]]

In [54]:
type(list3)

list

In [56]:
# DataFrame => Dict 로 변환
dict3 = df_dict_.to_dict()
dict3

{'kor': {0: 1, 1: 11}, 'eng': {0: 2, 1: 12}, 'mat': {0: 3, 1: 13}}

In [58]:
dict4 = df_dict_.to_dict('list')
dict4

{'kor': [1, 11], 'eng': [2, 12], 'mat': [3, 13]}

In [59]:
titanic_df = pd.read_csv(
    r'./data/titanic_train.csv'
)

In [60]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [63]:
a = titanic_df.columns

In [67]:
a

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [68]:
# DataFrame 에 컬럼 추가, 수정
# 1. dict 형식 이용하는 방식
# 2. 소유(.) 이용하는 방식


{'a': 1, 'b': 2}

In [75]:
d1 = {'a':1,'b':2}
d1

d1['c'] = [1,2,3]
d1['d'] = {1,2,3}
d1['e'] = {1:2, 2:3,3:4}
d1


{'a': 1, 'b': 2, 'c': [1, 2, 3], 'd': {1, 2, 3}, 'e': {1: 2, 2: 3, 3: 4}}

In [89]:
titanic_df['Age_0'] = list(range(1,892))
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  \
0        0         A/5 21171   7.2500   NaN        S      1   
1        0          PC 17599  71.2833   C85        C      2   
2        0  STON/O2. 3101282   7.9250   NaN        S      3   
3        0            113803  53.1000  C123        S      4   
4        0            373450   8.0500   NaN        S      5   
..     ...               ...      ...   ...      ...    ...   
886      0            211536  13.0000   NaN        S    887   
887      0            112053  30.0000   B42        S    888   
888      2        W./C. 6607  23.4500   NaN        S    889   
889      0            111369  30.0000  C148        C    890   
890      0            370376   7.7500   NaN        Q    891   

    (Age_0, Embarked_0)  
0                  None  
1                  None  
2                  None  
3                  None  
4                  None  
..                  ...  
886                None  
887                None  
888                None  
889                None  
890                None  

[891 rows x 14 columns]

In [90]:
# titanic_df['컬럼명'] => 컬럼에 있는 데이터 확인
# value 는 ndarray 에 저장되어 있다.
# ndarray 는 루프 없이 반복된다. 
titanic_df['Age_0']

0        1
1        2
2        3
3        4
4        5
      ... 
886    887
887    888
888    889
889    890
890    891
Name: Age_0, Length: 891, dtype: int64

In [91]:
# 브로드 캐스팅 예제
list5 = [
    [1,2]
  , [3,4]
]
list5

[[1, 2], [3, 4]]

In [93]:
arr_list5= np.array(list5)
arr_list5

array([[1, 2],
       [3, 4]])

In [94]:
arr2 = arr_list5*10
arr2

array([[10, 20],
       [30, 40]])

In [96]:
arr2.ndim

2

In [97]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  \
0        0         A/5 21171   7.2500   NaN        S      1   
1        0          PC 17599  71.2833   C85        C      2   
2        0  STON/O2. 3101282   7.9250   NaN        S      3   
3        0            113803  53.1000  C123        S      4   
4        0            373450   8.0500   NaN        S      5   
..     ...               ...      ...   ...      ...    ...   
886      0            211536  13.0000   NaN        S    887   
887      0            112053  30.0000   B42        S    888   
888      2        W./C. 6607  23.4500   NaN        S    889   
889      0            111369  30.0000  C148        C    890   
890      0            370376   7.7500   NaN        Q    891   

    (Age_0, Embarked_0)  
0                  None  
1                  None  
2                  None  
3                  None  
4                  None  
..                  ...  
886                None  
887                None  
888                None  
889                None  
890                None  

[891 rows x 14 columns]

In [98]:
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch']+1

In [99]:
titanic_df


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_0  \
0        0         A/5 21171   7.2500   NaN        S      1   
1        0          PC 17599  71.2833   C85        C      2   
2        0  STON/O2. 3101282   7.9250   NaN        S      3   
3        0            113803  53.1000  C123        S      4   
4        0            373450   8.0500   NaN        S      5   
..     ...               ...      ...   ...      ...    ...   
886      0            211536  13.0000   NaN        S    887   
887      0            112053  30.0000   B42        S    888   
888      2        W./C. 6607  23.4500   NaN        S    889   
889      0            111369  30.0000  C148        C    890   
890      0            370376   7.7500   NaN        Q    891   

    (Age_0, Embarked_0)  Family_No  
0                  None          2  
1                  None          2  
2                  None          1  
3                  None          2  
4                  None          1  
..                  ...        ...  
886                None          1  
887                None          1  
888                None          4  
889                None          1  
890                None          1  

[891 rows x 15 columns]

In [106]:
titanic_df = titanic_df.drop(('Age_0','Embarked_0'), axis = 1)

In [107]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Family_No  
0        0         A/5 21171   7.2500   NaN        S          2  
1        0          PC 17599  71.2833   C85        C          2  
2        0  STON/O2. 3101282   7.9250   NaN        S          1  
3        0            113803  53.1000  C123        S          2  
4        0            373450   8.0500   NaN        S          1  
..     ...               ...      ...   ...      ...        ...  
886      0            211536  13.0000   NaN        S          1  
887      0            112053  30.0000   B42        S          1  
888      2        W./C. 6607  23.4500   NaN        S          4  
889      0            111369  30.0000  C148        C          1  
890      0            370376   7.7500   NaN        Q          1  

[891 rows x 13 columns]

In [128]:
titanic_df2 = titanic_df.drop([])

SyntaxError: invalid syntax (<ipython-input-128-8210ecef019f>, line 1)

In [127]:
titanic_df2.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
5            6         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
5                                   Moran, Mr. James    male   NaN      0   

   Parch     Ticket     Fare Cabin Embarked  Family_No  
0      0  A/5 21171   7.2500   NaN        S          2  
1      0   PC 17599  71.2833   C85        C          2  
5      0     330877   8.4583   NaN        Q          1

In [123]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Family_No  
0      0         A/5 21171   7.2500   NaN        S          2  
1      0          PC 17599  71.2833   C85        C          2  
2      0  STON/O2. 3101282   7.9250   NaN        S          1