In [2]:
import numpy as np

In [5]:
#불린 인덱싱: 조건 필터링과 검색

arr1d= np.arange(1,10)
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [18]:
#리스트로 생성해서 ndarray와 비교
list1d = list(range(1,10))
result = [] #결과 저장할 리스트 생성
for n in list1d:
    if n>5:
        result.append(n)
        
result

[6, 7, 8, 9]

In [7]:
arr1d[arr1d>5]

array([6, 7, 8, 9])

In [8]:
bool_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])

In [9]:
arr3 = arr1d[bool_indexes]

In [10]:
arr3

array([6, 7, 8, 9])

In [11]:
indexes = np.array([5,6,7,8])

In [12]:
arr4 = arr1d[indexes]

In [13]:
arr4

array([6, 7, 8, 9])

In [ ]:
# 행렬 정렬
# np.sort() => function
# ndarray.sort() => member method

In [15]:
org_arr = np.array([3,1,9,5])
org_arr

array([3, 1, 9, 5])

In [18]:
sort_arr = np.sort(org_arr)
print(sort_arr)
print(org_arr)

[1 3 5 9]
[3 1 9 5]


In [20]:
sort_arr2 = org_arr.sort()
print(sort_arr2)
print(org_arr)

None
[1 3 5 9]


In [32]:
sort_arr = np.sort(org_arr)[::-1]
print(sort_arr)
print(org_arr)

[9 5 3 1]
[1 3 5 9]


In [23]:
arrd = np.array([3,2,8,7])
arrd

array([3, 2, 8, 7])

In [30]:
sort_arrd = np.sort(arrd)[::-2]
print(sort_arrd)
print(arrd)

[8 3]
[2 3 7 8]


In [28]:
sort_arrd2 = arrd.sort()
print(sort_arrd2)
print(arrd)

None
[2 3 7 8]


In [ ]:
#2차원 이상 행렬의 sort() => axis 축값 설정을 통해.

In [34]:
arr = np.array([8,12,7,1])
arr

array([ 8, 12,  7,  1])

In [36]:
arr2d = arr.reshape(2,2)
arr2d

array([[ 8, 12],
       [ 7,  1]])

In [44]:
sort_arr2d_axis0 = np.sort(arr2d,axis=0)
sort_arr2d_axis0

array([[ 7,  1],
       [ 8, 12]])

In [45]:
sort_arr2d_axis0 = np.sort(arr2d,axis=1)
sort_arr2d_axis0

array([[ 8, 12],
       [ 1,  7]])

In [46]:
sort_arr2d_axis0 = np.sort(arr2d)
sort_arr2d_axis0

array([[ 8, 12],
       [ 1,  7]])

In [48]:
org_arr = np.array([3,1,9,5])
org_arr

array([3, 1, 9, 5])

In [50]:
sort_indices = np.argsort(org_arr)[::-1]
sort_indices

array([2, 3, 0, 1], dtype=int64)

In [51]:
name_arr = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_arr= np.array([78, 95,84, 98,88])

In [53]:
sort_indices_asc = np.argsort(score_arr)
print(sort_indices_asc)
print(name_arr[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [4]:
A = np.arange(1,7)
B = np.arange(7,13)
print(A,B)

[1 2 3 4 5 6] [ 7  8  9 10 11 12]


In [6]:
A = A.reshape(2,3)
B = B.reshape(3,2)
print(A,'\n' ,B)

[[1 2 3]
 [4 5 6]] 
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [7]:
dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [8]:
transpose_A = np.transpose(A)
transpose_A


array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
transpose_B = np.transpose(B)
print(B)
print(transpose_B)

[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 7  9 11]
 [ 8 10 12]]
