In [1]:
import numpy as np

In [3]:
arr1 = np.arange(10)
print(arr1)
print(arr1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [9]:
arr2= arr1.reshape(2,5)
print(arr2)
print(arr2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [11]:
arr3= arr1.reshape(5,2)
print(arr2)
print(arr2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [13]:
arr4= arr1.reshape(-1,5)
print(arr4)
print(arr4.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [14]:
arr5= arr1.reshape(5,-1)
print(arr5)
print(arr5.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


In [19]:
arr6= arr1.reshape(-1,1)
print(arr6)
print(arr6.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [ ]:
arr6= arr1.reshape(1,-1)
print(arr6)
print(arr6.shape)

In [21]:
arr1= np.arange(8)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
arr3d = arr1.reshape((2,2,2))
arr3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
arr5 = arr3d.reshape(-1,1)
print(arr5.tolist())
arr5.shape

[[0], [1], [2], [3], [4], [5], [6], [7]]


(8, 1)

In [ ]:
#Indexing

In [51]:
arr1 = np.arange(start=1,stop=10,step=1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
value = arr1[3]
print(value)
print(type(value))
print('맨 뒤의 값:',arr1[-1])
print('맨 뒤를 제외한 모든 리스트:\n',arr1[:-1])
print('모든 리스트:\t', arr1[:])
print('뒤에서 두번째 값 :', arr1[-2])

4
<class 'numpy.int32'>
맨 뒤의 값: 9
맨 뒤를 제외한 모든 리스트:
 [1 2 3 4 5 6 7 8]
모든 리스트:	 [1 2 3 4 5 6 7 8 9]
뒤에서 두번째 값 : 8


In [46]:
print("Life is too short", end = " ")
print("You need python")

Life is too short You need python


In [67]:
arr1[1] = 3

In [68]:
print('맨 뒤의 값:',arr1[-1])
print('맨 뒤를 제외한 모든 리스트:\n',arr1[:-1])
print('모든 리스트:\t', arr1[:])
print('뒤에서 두번째 값 :', arr1[-2])

맨 뒤의 값: 9
맨 뒤를 제외한 모든 리스트:
 [1 3 3 4 5 6 7 8]
모든 리스트:	 [1 3 3 4 5 6 7 8 9]
뒤에서 두번째 값 : 8


In [71]:
#2차원에서 추출
arr1d = np.arange(1,10)
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr2d = arr1d.reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
print(arr2d[0,0], end=' ')
print(arr2d[1,1], end = ' ')
print(arr2d[2,2])
arr2d[2,2]

1 5 9


9

In [87]:
arr1 = np.arange(start=1, stop=10)
print(arr1)
arr2 = arr1[:3]
print(arr2)
print(type(arr1), type(arr2))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [91]:
arr3 = arr1[:]
arr4 = arr1[:-1]
arr5 = arr1[3:]
arr6 = arr1[:3]
print(arr3, arr4, arr5, arr6)

[1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8] [4 5 6 7 8 9] [1 2 3]


In [95]:
print(id(arr1), id(arr3))
print(arr1, arr3)

2701651176384 2701651022032
[1 2 3 4 5 6 7 8 9] [1 2 3 4 5 6 7 8 9]


In [108]:
arr1[1] = 20
print(arr1, arr3)

[1, 20, 3, 4, 5, 6, 7, 8, 9] [ 1 20  3  4  5  6  7  8  9]


In [98]:
!python -V

Python 3.8.3


In [99]:
arr1

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9])

In [100]:
arr3

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9])

In [101]:
arr1 = [1,2,3,4,5,6,7,8,9]

In [102]:
type(arr1)

list

In [103]:
arr2 = arr1[:]

In [104]:
arr1, arr2

([1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
arr2[0] = 10

In [106]:
arr1,arr2

([1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
type(arr1)

list

In [112]:
arr1d = np.arange(1,10)
arr2d = arr1d.reshape(3,3)
print(arr1d, '\n', arr2d)

[1 2 3 4 5 6 7 8 9] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [114]:
print(arr2d[0:, 0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [117]:
print(arr2d[0:2, 1:])

[[2 3]
 [5 6]]


In [128]:
print(arr2d[1:,0:])

[[4 5 6]
 [7 8 9]]


In [129]:
print(arr2d[:2, 0:1])

[[1]
 [4]]


In [130]:
print(arr2d[:2, :2])

[[1 2]
 [4 5]]


In [131]:
print(arr2d[:5, :5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [140]:
arr22 = arr2d[:2,0]
print(arr22)
print(arr22.shape)
print(arr22.ndim)

[1 4]
(2,)
1


In [133]:
print(arr2d[0,0])

1


In [135]:
print(arr2d[1,2])

6


In [144]:
arr11 = arr2d[0]
print(arr11)
print(arr11.ndim)


[1 2 3]
1


In [145]:
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [159]:
arr2d[[0,2],0:2]

array([[1, 2],
       [7, 8]])

In [161]:
arr2d[[0,2],[0,1]]

array([1, 8])