In [3]:
import numpy as np

In [26]:
# [1,2,3] => ndarray object 생성
# ndarray object 변수
# shape : 배열 크기, ndim: 배열 차원
arr1 = np.array([1,2,3])
print('arr1 type:' , type(arr1))
print('arr1 형태:' , arr1.shape)


arr1 type: <class 'numpy.ndarray'>
arr1 형태: (3,)


In [25]:
arr2 = np.array([
       [1,2]
      ,[4,5]
      ,[7,8]
                ])
print(type(arr2));
print(arr2.shape);
print(arr2.ndim);

<class 'numpy.ndarray'>
(3, 2)
2


In [27]:
arr3 = np.array([[1,2,3]])

In [30]:
print(type(arr3))
print(arr2.shape)
print(arr2.ndim)

<class 'numpy.ndarray'>
(3, 2)
2


In [32]:
list1 = [1,2,3]

In [35]:
list1?

In [37]:
print(type(list1))

<class 'list'>


In [39]:
array1 = np.array(list1)

In [42]:
print(array1, array1.dtype)

[1 2 3] int32


In [44]:
list2= [1,2,'test']

In [46]:
type(list2)

list

In [48]:
array2 = np.array(list2)

In [50]:
type(array2)

numpy.ndarray

In [53]:
array2.dtype

dtype('<U11')

In [55]:
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [57]:
a = 'test'

In [58]:
type(a)

str

In [59]:
list3 = [1,2,3.0]

In [60]:
array3 = np.array(list3)

In [61]:
print(array3.dtype)

float64


In [62]:
print(array3)

[1. 2. 3.]


In [65]:
arr_int = np.array([1,2,3])
arr_float = arr_int.astype('float64')
print(arr_float, arr_float.dtype)

[1. 2. 3.] float64


In [66]:
arr_int1= arr_float.astype('int32')
print(arr_int1, arr_int1.dtype)

[1 2 3] int32


In [67]:
arr_float1 = np.array([1.1,2.1,3.1])
arr_int2 = arr_float1.astype('int32')
print(arr_int2, arr_int2.dtype)

[1 2 3] int32


In [69]:
sequence_arr = np.arange(10)
print(sequence_arr)
print(sequence_arr.dtype, sequence_arr.shape, sequence_arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,) 1


In [71]:
zero_arr = np.zeros((3,2))
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape, zero_arr.ndim)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2) 2


In [72]:
zero_arr = np.zeros((3,2), dtype='int32')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape, zero_arr.ndim)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 2


In [72]:
zero_arr = np.zeros((3,2), dtype='int32')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape, zero_arr.ndim)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2) 2


In [73]:
one_arr = np.ones((3,2), dtype='int32')
print(one_arr)
print(one_arr.dtype, one_arr.shape, one_arr.ndim)

[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2) 2
