In [1]:
import numpy as np
import pandas as pd

In [3]:
titanic_df = pd.read_csv('./data/titanic_train.csv')

In [5]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [6]:
indexes = titanic_df.index

In [8]:
type(indexes)

pandas.core.indexes.range.RangeIndex

In [19]:
titanic_df2 = titanic_df.drop([0,1,2,3], axis = 0)

In [20]:
titanic_df2

PassengerId  Survived  Pclass  \
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch      Ticket     Fare Cabin Embarked  
4        0      373450   8.0500   NaN        S  
5        0      330877   8.4583   NaN        Q  
6        0       17463  51.8625   E46        S  
7        1      349909  21.0750   NaN        S  
8        2      347742  11.1333   NaN        S  
..     ...         ...      ...   ...      ...  
886      0      211536  13.0000   NaN        S  
887      0      112053  30.0000   B42        S  
888      2  W./C. 6607  23.4500   NaN        S  
889      0      111369  30.0000  C148        C  
890      0      370376   7.7500   NaN        Q  

[887 rows x 12 columns]

In [22]:
indexes2 = titanic_df2.index
indexes2

Int64Index([  4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
            ...
            881, 882, 883, 884, 885, 886, 887, 888, 889, 890],
           dtype='int64', length=887)

In [9]:
indexes

RangeIndex(start=0, stop=891, step=1)

In [10]:
indexes.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [23]:
print(indexes2[:5].values)
print(indexes2.values[:5])

[4 5 6 7 8]
[4 5 6 7 8]


In [12]:
indexes2 = range(1,10)

In [13]:
indexes2

range(1, 10)

In [24]:
series_fair = titanic_df['Fare']

In [25]:
series_fair

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [26]:
print(series_fair.max())
print(series_fair.min())
print(series_fair.sum())
print(sum(series_fair))

512.3292
0.0
28693.9493
28693.949299999967


In [27]:
print((series_fair+3).head(3))

0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [28]:
print((series_fair).head(3))

0     7.2500
1    71.2833
2     7.9250
Name: Fare, dtype: float64


In [34]:
titanic_reset_df2= titanic_df2.reset_index()

In [36]:
titanic_reset_df2


index  PassengerId  Survived  Pclass  \
0        4            5         0       3   
1        5            6         0       3   
2        6            7         0       1   
3        7            8         0       3   
4        8            9         1       3   
..     ...          ...       ...     ...   
882    886          887         0       2   
883    887          888         1       1   
884    888          889         0       3   
885    889          890         1       1   
886    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                             Allen, Mr. William Henry    male  35.0      0   
1                                     Moran, Mr. James    male   NaN      0   
2                              McCarthy, Mr. Timothy J    male  54.0      0   
3                       Palsson, Master. Gosta Leonard    male   2.0      3   
4    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ...    ...   
882                              Montvila, Rev. Juozas    male  27.0      0   
883                       Graham, Miss. Margaret Edith  female  19.0      0   
884           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
885                              Behr, Mr. Karl Howell    male  26.0      0   
886                                Dooley, Mr. Patrick    male  32.0      0   

     Parch      Ticket     Fare Cabin Embarked  
0        0      373450   8.0500   NaN        S  
1        0      330877   8.4583   NaN        Q  
2        0       17463  51.8625   E46        S  
3        1      349909  21.0750   NaN        S  
4        2      347742  11.1333   NaN        S  
..     ...         ...      ...   ...      ...  
882      0      211536  13.0000   NaN        S  
883      0      112053  30.0000   B42        S  
884      2  W./C. 6607  23.4500   NaN        S  
885      0      111369  30.0000  C148        C  
886      0      370376   7.7500   NaN        Q  

[887 rows x 13 columns]

In [37]:
titanic_df2

PassengerId  Survived  Pclass  \
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch      Ticket     Fare Cabin Embarked  
4        0      373450   8.0500   NaN        S  
5        0      330877   8.4583   NaN        Q  
6        0       17463  51.8625   E46        S  
7        1      349909  21.0750   NaN        S  
8        2      347742  11.1333   NaN        S  
..     ...         ...      ...   ...      ...  
886      0      211536  13.0000   NaN        S  
887      0      112053  30.0000   B42        S  
888      2  W./C. 6607  23.4500   NaN        S  
889      0      111369  30.0000  C148        C  
890      0      370376   7.7500   NaN        Q  

[887 rows x 12 columns]

In [41]:
# titanic_df['Pclass'] => Series
# Pclass => 1등칸, 2등칸, 3등칸
value_counts = titanic_df['Pclass'].value_counts()
value_counts

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [42]:
type(value_counts)

pandas.core.series.Series

In [51]:
new_value_counts= value_counts.reset_index()
new_value_counts

index  Pclass
0      3     491
1      1     216
2      2     184

In [52]:
type(new_value_counts)

pandas.core.frame.DataFrame

In [63]:
print(titanic_df['Pclass'].head(3))
# 팬시 인덱싱(p.62)
print(titanic_df[['Pclass','Age']].head(3))

0    3
1    1
2    3
Name: Pclass, dtype: int64
   Pclass   Age
0       3  22.0
1       1  38.0
2       3  26.0


In [59]:
a = titanic_df['Embarked'].head(3)
type(a)

pandas.core.series.Series

In [60]:
a2 = a.reset_index()

In [61]:
a2

index Embarked
0      0        S
1      1        C
2      2        S

In [62]:
type(a2)

pandas.core.frame.DataFrame

In [65]:
# == : 비교연산자 => 결과:bool => True, False
# Series => ndarray => 브로드캐스팅 가능 : 즉 루프없이 반복 => 불린 인덱싱의경우 True 인 애들의 인덱스값을 전부 가져와서 해당 row 를 모두 출력하게 된다.
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

In [77]:
print(titanic_df.ix[0,'Pclass'])

AttributeError: 'DataFrame' object has no attribute 'ix'

In [79]:
data = {
        'Name':['Chumlmin','Eunkyung','Jinwoong','Soobeom']
       ,'Year':[2011,2016,2015,2015]
       ,'Gender':['Male','Female','Male','Male']  
       }
data

{'Name': ['Chumlmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
 'Year': [2011, 2016, 2015, 2015],
 'Gender': ['Male', 'Female', 'Male', 'Male']}

In [84]:
indexes = ['one','two','three','four']

data_df.index = indexes
data_df = pd.DataFrame(data, index = indexes)
data_df

Name  Year  Gender
one    Chumlmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [83]:
pd.DataFrame?

In [87]:
indexes = ['one','two','three','four']

data_df.index = indexes
data_df
data_df.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [88]:
data_df_reset = data_df.reset_index()
data_df_reset

index      Name  Year  Gender
0    one  Chumlmin  2011    Male
1    two  Eunkyung  2016  Female
2  three  Jinwoong  2015    Male
3   four   Soobeom  2015    Male

In [89]:
data_df_reset = data_df_reset.rename(columns={'index':'old_index'})

In [90]:
data_df_reset

old_index      Name  Year  Gender
0       one  Chumlmin  2011    Male
1       two  Eunkyung  2016  Female
2     three  Jinwoong  2015    Male
3      four   Soobeom  2015    Male

In [92]:
data_df_reset.rename?

In [93]:
data_df_reset.index = data_df_reset.index+1
data_df_reset

old_index      Name  Year  Gender
1       one  Chumlmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [94]:
data_df_reset.ix[1,1]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [96]:
a = titanic_df.index
type(a)

pandas.core.indexes.range.RangeIndex

In [98]:
b =a.values
type(b)

numpy.ndarray

In [99]:
a = titanic_df.index.values

In [100]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [101]:
a[0]

0

In [102]:
a[3]

3

In [104]:
a[3] =4

In [105]:
a[3]

4

In [106]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [107]:
type(a)

numpy.ndarray

In [109]:
b = titanic_df.index
b

RangeIndex(start=0, stop=891, step=1)

In [110]:
b[0] = 1

TypeError: Index does not support mutable operations